export const SEND_INVITE_START = 'SEND_INVITE_START';
export const SEND_INVITE_SUCCESS = 'SEND_INVITE_SUCCESS';
export const SEND_INVITE_FAIL = 'SEND_INVITE_FAIL';
export const VALIDATE_EMAIL_START = 'VALIDATE_EMAIL_START';
export const VALIDATE_EMAIL_SUCCESS = 'VALIDATE_EMAIL_SUCCESS';
export const VALIDATE_EMAIL_FAIL = 'VALIDATE_EMAIL_FAIL';

export const TEST = 'TEST';
